services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:24
    restart: unless-stopped
    volumes:
      - ./workspace:/opt/cloudbeaver/workspace
    networks:
      - traefik
      - dbeaver
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cloudbeaver.rule=Host(`dbeaver.${DOMAIN_NAME}`)"
      - "traefik.http.routers.cloudbeaver.middlewares=auth-http-admin@file"

networks:
  traefik:
    external: true
  dbeaver:
    external: true
