services:
  traefik:
    image: traefik:v3
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      # Mount server's timezone
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Access to Docker
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Static config
      - ./traefik.yml:/traefik.yml:ro
      # Dynamic config
      - ./config:/config:ro
      # SSL certificates
      - ./certificates:/certificates
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik-dashboard.middlewares=auth-require-login@file,auth-require-group-admin-vps@file"

  error-pages:
    image: tarampampam/error-pages:3
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      TEMPLATE_NAME: matrix
      READ_BUFFER_SIZE: 6144
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.error-pages.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.error-pages.priority=1"
      - "traefik.http.routers.error-pages.middlewares=error-pages"

      # "errors" middleware settings
      - "traefik.http.middlewares.error-pages.errors.status=400-599"
      - "traefik.http.middlewares.error-pages.errors.service=error-pages"
      - "traefik.http.middlewares.error-pages.errors.query=/{status}.html"
      - "traefik.http.services.error-pages.loadbalancer.server.port=8080"

networks:
  traefik:
    external: true
  monitoring:
    external: true
