version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    environment:
      - PMA_HOSTS=${PMA_HOSTS_LIST}
      - PMA_ABSOLUTE_URI=https://phpmyadmin.${DOMAIN_NAME}/
      - UPLOAD_LIMIT=100M
    restart: unless-stopped
    networks:
      - proxy
      - phpmyadmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.${DOMAIN_NAME}`)"
      - "traefik.http.routers.phpmyadmin.middlewares=auth-http-admin@file"

networks:
  proxy:
    external: true
  phpmyadmin:
    external: true
