version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      # Mount server's timezone
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Access to Docker
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Static config
      - ./traefik.yml:/traefik.yml:ro
      # Dynamic config
      - ./config:/config:ro
      # SSL certificates
      - ./certificates:/certificates
      # HTTP Auth
      - ./auth-http-users:/auth-http-users:ro
    networks:
      - proxy
      - monitoring
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik-secure.middlewares=auth-http-admin@file"
      # - "traefik.http.routers.traefik-secure.middlewares=dashboard-ipwhitelist@file"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  proxy:
    external: true
  monitoring:
    external: true
