version: '3.8'

services:
  traefik:
    image: traefik:v2.9.8
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      # Add folder with dynamic configuration yml and certificates
      - ./certificates:/certificates
      - ./config:/config
      # Retrieve logs
      - ./logs:/var/log/traefik/
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik-secure.middlewares=dashboard-user-auth@file"
      # - "traefik.http.routers.traefik-secure.middlewares=dashboard-ipwhitelist@file"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  proxy:
    external: true
