api:
  dashboard: true

log:
  level: ERROR # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: common # common, json, logfmt

accesslog:
  format: common # common, json, logfmt

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
    http:
      middlewares:
        - nofloc@file
        - secureHeaders@file
      tls:
        certResolver: letsencrypt

  sftp:
    address: :2223

  metrics:
    address: :8080

pilot:
  dashboard: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /config
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: thomas.ritaine@outlook.com
      storage: /certificates/acme.json
      tlschallenge: true

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
