api:
  dashboard: true

# (Optional) Log information
log:
  level: ERROR # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: common # common, json, logfmt
  filePath: /var/log/traefik/error.log

# (Optional) Accesslog
accesslog:
  format: common # common, json, logfmt
  filePath: /var/log/traefik/access.log

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
    http:
      middlewares:
        - nofloc@file
        - secureHeaders@file
      tls:
        certResolver: letsencrypt

  sftp:
    address: :2223

pilot:
  dashboard: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config/dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: thomas.ritaine@outlook.com
      storage: /certificates/acme.json
      tlschallenge: true
