http:
  middlewares:
    auth-http-admin:
      basicAuth:
        usersFile: /auth-http-users/admin.htpasswd

    auth-http-private-transfer:
      basicAuth:
        usersFile: /auth-http-users/private-transfer.htpasswd

    # ipwhitelist-admin:
    #   ipwhitelist:
    #     sourcerange:
    #       - "167.114.36.33"
